name: Push to EPITECH

on:
  push:
    branches: [ '**', '!ga-ignore-*' ]
  pull_request:
    branches: [ '**', '!ga-ignore-*' ]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-CPP-500-BDX-5-2-rtype-max.peixoto.git

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push the repository to a mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasio-dev
        sudo apt-get install -y libsfml-dev
    - name: Run build script
      run: ./build.sh
    - name: Check binaries
      run: |
        test -f r-type_client && echo "r-type_client binary exists."
        test -f r-type_server && echo "r-type_server binary exists."
    - name: Upload binaries for testing
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          r-type_client
          r-type_server

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries
    - name: Set execute permission on binaries
      run: |
        chmod +x r-type_server
        chmod +x r-type_client
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run server
      run: |
        ./r-type_server &
        echo "SERVER_PID=$!" >> $GITHUB_ENV
    - name: Run integration test
      run: python3 server/server_test_one_client.py
    - name: Kill server
      run: kill $SERVER_PID || true
